# version: '3.8'

# services:
#   mongo:
#     image: mongo
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: hammerspace
#       MONGO_INITDB_ROOT_PASSWORD: hammerspace
#       MONGO_INITDB_DATABASE: hammerspace
#     volumes:
#       - ./mongo-data:/data/db
#       - ./database/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#     expose:
#       - 27017:27017

#   # postgres:
#   #   image: postgres:14-alpine
#   #   restart: always
#   #   command: postgres
#   #   environment:
#   #     - POSTGRES_PASSWORD=postgres
#   #   ports:
#   #     - 9132:5432
#   #   volumes: 
#   #     - ./postgres-data:/var/lib/postgresql/data
#   #     - ./database/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

# volumes:
#   mongo-data:
#     driver: local
#   # postgres-data:
#   #   driver: local
version: '3.1'

services:

  gatosexy:
    image: mongo
    restart: always
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hammerspace
      MONGO_INITDB_ROOT_PASSWORD: hammerspace
      MONGO_INITDB_DATABASE: hammerspace
    volumes: 
    - ./mongo-data:/data/db
    - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
